name: Check Zammad Health

on:
  schedule:
    - cron: '*/5 * * * *'
    
  workflow_dispatch:

jobs:
  check_status:
    strategy:
        matrix:
          environment: [flightmarket, finsverka]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
    - name: Check status page
      run: |
        response=$(curl -s https://${{ secrets.ZAMMAD_HOST }}/api/v1/monitoring/health_check?token=${{ secrets.ZAMMAD_TOKEN }})
        if [ $? -ne 0 ]; then
            ERROR_MSG="Error : Failed to fetch status page for zammad ${{ matrix.environment }}"
            echo "$ERROR_MSG"
            curl -X POST -H 'Content-type: application/json' --data '{"channel": "#devops-duty", "username": "github_external_monitor", "text":"$ERROR_MSG"}' ${{ secrets.SLACK_WEBHOOK_URL }}
            exit 1
        fi
        healthy=$(echo $response | jq -r '.healthy')
        if [ "$healthy" != "false" ]; then
          ERROR_MSG="Error : Status page of zammad ${{ matrix.environment }} is not healthy"
          echo "$ERROR_MSG"
          curl -X POST -H 'Content-type: application/json' --data '{"channel": "#devops-duty", "username": "github_external_monitor", "text":"$ERROR_MSG"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          exit 1
        else
          echo "Status page is healthy"
        fi
