name: Check Zammad Health

on:
  schedule:
    - cron: '*/5 * * * *'
    
  workflow_dispatch:

jobs:
  check_status:
    strategy:
        matrix:
          environment: [flightmarket, finsverka]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
    - name: Check status page
      run: |
        post_to_slack() {
          message=$1
          echo "$message"
          curl -X POST -H 'Content-type: application/json' --data "{\"channel\": \"#devops-duty\", \"username\": \"github_external_monitor\", \"text\":\"$message\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
        }
        
        response=$(curl -s https://${{ secrets.ZAMMAD_HOST }}/api/v1/monitoring/health_check?token=${{ secrets.ZAMMAD_TOKEN }})
        if [ $? -ne 0 ]; then
            post_to_slack "Error : Failed to fetch status page for zammad ${{ matrix.environment }}"
            exit 1
        fi
        healthy=$(echo $response | jq -r '.healthy')
        if [ "$healthy" != "false" ]; then
          post_to_slack "Error : Status page of zammad ${{ matrix.environment }} is not healthy"
          exit 1
        else
          echo "Status page is healthy"
        fi
